privacy:
  local_processing_only: true
  data_retention_days: 30
  encryption_enabled: true
  
permissions:
  allow_network: false
  allow_storage: true
  allow_camera: false
  allow_microphone: false
  
data_flow:
  monitor_inputs: true
  monitor_outputs: true
  redact_personal_info: true
  audit_logging: true